#define FORK_PIN 14
#define ADC_PIN 29
#define NUM_POSITIONS 10

// TFT
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

// Canvas
#define CANVAS_BACKGROUND 0x20E6
#define CANVAS_WIDTH 320
#define CANVAS_HEIGHT 220

// Tab Area
#define TAB_CORNER_RADIUS 2
#define TAB_AREA_BACKGROUND 0x5AEC
#define TAB_INACTIVE_BG 0x39C8
#define TAB_ACTIVE_TEXT 0xFFFF
#define TAB_INACTIVE_TEXT 0x5AEC
#define TAB_ACTIVE_BG 0x20E6
#define TAB_AREA_HEIGHT 20
#define TAB_SPACING 2
#define TAB_HEIGHT 20
#define TAB_WIDTH 80